-- :fennel:1719610873
local p = require("packages")
p.setup()
require("impatient")
require("theme")
require("options")
require("lualine.themes.gruvbox-material")
require("nvim_comment").setup()
require("bufferline").setup()
require("gitlinker").setup()
require("oil_manager")
require("bindings")
require("markdown")
require("lib")
require("lualine_manager")
require("coding.snippets")
require("coding.dap")
require("coding.lsp")
require("coding.autocompletition")
require("coding.on_attach")
require("coding.treesitter")
require("coding.elixir-tools")
return require("autogroups")